Fixed setting up mocks with the new firebase_core_platform_interface
sitatec/firebase_database_mocks pull request #6
Opened 2022-07-11 09:28 UTC by OlegNovosad

- [ ] Fixed setting up mocks with the new firebase_core_platform_interface version
- [ ] Updated dependencies

2022-07-20 14:01 UTC, OlegNovosad commented
> Might as well move `flutter_lints` and `fluter_test` to `dev_dependencies` in `pubspec.yaml`, I suppose they belong there actually.

Done.

2022-07-24 08:36 UTC, OlegNovosad commented
@sitatec I've also updated Github Actions build script with next improvements:

- Use the latest stable flutter
- Changed `runs-on` from `macos-latest` to `ubuntu-latest` to minimize actions time spent as macos minute is treated as 10 ubuntu minutes

2022-07-24 09:34 UTC, Zohenn commented
Cool, that's what caused my PR to fail to build. I wanted to make similar changes, but now I'll wait for @sitatec to merge your PR.

2022-07-24 12:08 UTC, sitatec requested changes
Thanks for your contribution @OlegNovosad. We just need to revert one change before merging.

2022-07-24 12:08 UTC, sitatec commented on test/mock_database_reference_test.dart
>      });
We need to revert this change. This test is for the `reference` method not for the `ref` one, the `ref` method has it own tests.
Although the `reference` method is deprecated, it hasn't been removed yet.

2022-07-24 12:45 UTC, OlegNovosad commented on test/mock_database_reference_test.dart
>      });
Makes sense @sitatec ! Updated.

2022-07-24 13:51 UTC, sitatec approved these changes

2022-07-24 13:51 UTC, merged